version: '3'
services:
  account-service:
    build:
      context: ./account-service
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
  mongodb:
    image: mongo
    volumes:
      - ./data/db:/data/db
      - ./data/dumps:/dumps
    ports:
      - "27017:27017"
  # Add other services here...
